name: "Deploy"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: satisfactory-hcloud
  cancel-in-progress: false

jobs:
  deploy:
    name: "Deploy server"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Send Discord notification on workflow start
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **Satisfactory** server is now **starting up**. :factory:
            Please wait a few minutes. :hourglass:
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v2
      - name: Setup OpenTofu Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          backup_access_key = "${{ secrets.BACKUP_ACCESS_KEY }}"
          backup_secret_key = "${{ secrets.BACKUP_SECRET_KEY }}"
          backup_bucket     = "${{ secrets.BACKUP_BUCKET }}"
          backup_provider   = "${{ secrets.BACKUP_PROVIDER }}"
          backup_region     = "${{ secrets.BACKUP_REGION }}"
          backup_endpoint   = "${{ secrets.BACKUP_ENDPOINT }}"
          hcloud_token      = "${{ secrets.HCLOUD_TOKEN }}"
          hcloud_ssh_key    = "${{ secrets.HCLOUD_SSH_KEY }}"
          EOF
      - name: OpenTofu Init
        run: >
          tofu init
          -backend-config="access_key=${{ secrets.STATE_ACCESS_KEY }}"
          -backend-config="secret_key=${{ secrets.STATE_SECRET_KEY }}"
          -backend-config="bucket=${{ secrets.STATE_BUCKET }}"
          -backend-config="region=${{ secrets.STATE_REGION }}"
          -backend-config="endpoint=${{ secrets.STATE_ENDPOINT }}"
          -backend-config="key=terraform.tfstate"
      - name: OpenTofu Plan
        run: tofu plan -input=false
      - name: OpenTofu Apply
        id: apply
        run: |
          tofu apply -auto-approve -input=false
          echo "ip_address=$(tofu output -raw satisfactory_server_ip_address)" >> $GITHUB_OUTPUT
      - name: Send Discord notification on success
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **Satisfactory** server is **up**. :factory:
            It may take a few minutes until it is available in-game.
            To connect, open the _Server Manager_ and join:
            ```
            ${{ steps.apply.outputs.ip_address }}
            ```
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Send Discord notification on failure
        if: ${{ failure() }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            **Satisfactory** server **failed to start**. :warning:
            Please check build logs for details.
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}